#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
生成班级宠物园设备待机时钟专用高清字体
- 时间字体 time76: 76px ASCII 数字 + 冒号 (Heiti SC Medium)
- 日期字体 date40: 40px 中文字符 + 数字, 用于待机日期/星期
- 菜单图标字体 menu32: 32px 中文字符, 用于功能菜单 APP 图标首字
输出 LVGL 9 binfont 格式, 编译进固件 (C 数组), 由 lv_binfont_create_from_buffer 加载
依赖:
  pip install fonttools
  npm install lv_font_conv
"""
import argparse
import os
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TTC_PATH = "/System/Library/Fonts/STHeiti Medium.ttc"
FONT_FACE_INDEX = 1  # Heiti SC Medium
TEMP_TTF = "/tmp/heiti_sc_medium.ttf"
LV_FONT_CONV = "/Users/Terry/.workbuddy/binaries/node/workspace/node_modules/.bin/lv_font_conv"
NODE_BIN = "/Users/Terry/.workbuddy/binaries/node/versions/22.22.2/bin/node"

FIRMWARE_DIR = os.path.normpath(os.path.join(SCRIPT_DIR, "..", "firmware", "ClassPetDevice"))


def extract_face():
    from fontTools.ttLib import TTCollection
    print(f"[1/3] 抽取字体面 {FONT_FACE_INDEX} 从 {TTC_PATH} ...")
    coll = TTCollection(TTC_PATH)
    names = [f["name"].getDebugName(4) for f in coll.fonts]
    print("      可用字体面:", names)
    font = coll.fonts[FONT_FACE_INDEX]
    font.save(TEMP_TTF)
    print(f"      已保存临时 TTF -> {TEMP_TTF}")


def convert(name, symbols, size, bpp, out_path, compress=False):
    print(f"[2/3] 生成 {name} (size={size}, bpp={bpp}, chars={len(symbols)}) ...")
    cmd = [
        NODE_BIN, LV_FONT_CONV,
        "--font", TEMP_TTF,
        "--format", "bin",
        "--size", str(size),
        "--bpp", str(bpp),
        "--symbols", symbols,
        "-o", out_path,
    ]
    if not compress:
        cmd.append("--no-compress")
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        print(f"lv_font_conv 失败 ({name}):\n", r.stdout, r.stderr, file=sys.stderr)
        sys.exit(1)
    kb = os.path.getsize(out_path) / 1024.0
    print(f"      ✅ {out_path} ({kb:.1f} KB)")


def bin_to_c(name, bin_path, c_path, h_path):
    print(f"[3/3] 生成固件内嵌 C 数组 {os.path.basename(c_path)} ...")
    with open(bin_path, "rb") as f:
        data = f.read()
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    body = "\n".join(lines)

    var = f"{name}_bin"
    c_text = (
        f'#include "{os.path.basename(h_path)}"\n\n'
        f"/* LVGL bin font '{name}', generated by tools/gen_standby_fonts.py. Do not edit. */\n"
        f"const uint8_t {var}[] = {{\n"
        f"{body}\n"
        "};\n"
        f"const unsigned int {var}_len = (unsigned int)sizeof({var});\n"
    )
    h_text = (
        "#pragma once\n"
        "#include <stdint.h>\n"
        "#ifdef __cplusplus\n"
        "extern \"C\" {\n"
        "#endif\n"
        f"extern const uint8_t {var}[];\n"
        f"extern const unsigned int {var}_len;\n"
        "#ifdef __cplusplus\n"
        "}\n"
        "#endif\n"
    )
    with open(c_path, "w") as f:
        f.write(c_text)
    with open(h_path, "w") as f:
        f.write(h_text)
    print(f"      ✅ 已写入 {c_path} / {h_path} ({len(data)} 字节)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bpp", type=int, default=4, choices=[1, 2, 3, 4, 8])
    ap.add_argument("--compress", action="store_true", help="压缩字体(需 LV_USE_FONT_COMPRESSED=1)")
    args = ap.parse_args()

    os.makedirs(FIRMWARE_DIR, exist_ok=True)
    extract_face()

    # 1. 时间: 76px ASCII 数字 + 冒号
    time_symbols = "0123456789:"
    time_bin = os.path.join(SCRIPT_DIR, "time76.bin")
    convert("time76", time_symbols, 76, args.bpp, time_bin, args.compress)
    bin_to_c("time76", time_bin,
             os.path.join(FIRMWARE_DIR, "time76_bin.c"),
             os.path.join(FIRMWARE_DIR, "time76_bin.h"))

    # 2. 日期: 40px 数字 + 月日星期 + 空格(注意空格不能省略，否则日期中间显示方框)
    date_symbols = " 0123456789月日星期一二三四五六七八九十"
    date_bin = os.path.join(SCRIPT_DIR, "date40.bin")
    convert("date40", date_symbols, 40, args.bpp, date_bin, args.compress)
    bin_to_c("date40", date_bin,
             os.path.join(FIRMWARE_DIR, "date40_bin.c"),
             os.path.join(FIRMWARE_DIR, "date40_bin.h"))

    # 3. 菜单图标: 32px 首字，避免与标签重叠
    menu_symbols = "番语历单闹宠设"
    menu_bin = os.path.join(SCRIPT_DIR, "menu32.bin")
    convert("menu32", menu_symbols, 32, args.bpp, menu_bin, args.compress)
    bin_to_c("menu32", menu_bin,
             os.path.join(FIRMWARE_DIR, "menu32_bin.c"),
             os.path.join(FIRMWARE_DIR, "menu32_bin.h"))

    print("\n完成! 请重新编译烧录固件。")


if __name__ == "__main__":
    main()
